# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'
inhibit_all_warnings!

target 'Resturants' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Resturants
  pod 'Alamofire'
  pod 'AlamofireImage'

end
